package CadastroPacientes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author barba
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGeral = new javax.swing.JPanel();
        NovaConsulta = new javax.swing.JButton();
        ExcluirConsulta = new javax.swing.JButton();
        FinalizarConsulta = new javax.swing.JButton();
        TextoBoasVindas = new javax.swing.JLabel();
        NomePaciente = new javax.swing.JLabel();
        CPFPaciente = new javax.swing.JLabel();
        TelefonePaciente = new javax.swing.JLabel();
        DataConsulta = new javax.swing.JLabel();
        ClienteAntigo = new javax.swing.JRadioButton();
        EspacoNome = new javax.swing.JTextField();
        EspacoCPF = new javax.swing.JTextField();
        EspacoTelefone = new javax.swing.JTextField();
        EspacoData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NovaConsulta.setText("NOVA CONSULTA");

        ExcluirConsulta.setText("EXCLUIR CONSULTA");

        FinalizarConsulta.setText("FINALIZAR CONSULTA");

        TextoBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoBoasVindas.setText("Boas vindas ao sistema de agendamento");

        NomePaciente.setText("NOME PACIENTE");

        CPFPaciente.setText("CPF");

        TelefonePaciente.setText("TELEFONE");

        DataConsulta.setText("DATA CONSULTA");

        ClienteAntigo.setText("JÁ FOI CONSULTADO ANTES");

        EspacoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacoDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelGeralLayout = new javax.swing.GroupLayout(PainelGeral);
        PainelGeral.setLayout(PainelGeralLayout);
        PainelGeralLayout.setHorizontalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EspacoNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelGeralLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(TextoBoasVindas)))
                    .addComponent(NomePaciente)
                    .addComponent(CPFPaciente)
                    .addComponent(TelefonePaciente)
                    .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DataConsulta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelGeralLayout.createSequentialGroup()
                            .addComponent(NovaConsulta)
                            .addGap(38, 38, 38)
                            .addComponent(ExcluirConsulta)
                            .addGap(41, 41, 41)
                            .addComponent(FinalizarConsulta)))
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EspacoData)
                            .addComponent(EspacoTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EspacoCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addComponent(ClienteAntigo)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PainelGeralLayout.setVerticalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoBoasVindas)
                .addGap(18, 18, 18)
                .addComponent(NomePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspacoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CPFPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspacoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelefonePaciente)
                .addGap(4, 4, 4)
                .addComponent(EspacoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteAntigo)
                    .addComponent(EspacoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovaConsulta)
                    .addComponent(ExcluirConsulta)
                    .addComponent(FinalizarConsulta))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspacoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacoDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFPaciente;
    private javax.swing.JRadioButton ClienteAntigo;
    private javax.swing.JLabel DataConsulta;
    private javax.swing.JTextField EspacoCPF;
    private javax.swing.JTextField EspacoData;
    private javax.swing.JTextField EspacoNome;
    private javax.swing.JTextField EspacoTelefone;
    private javax.swing.JButton ExcluirConsulta;
    private javax.swing.JButton FinalizarConsulta;
    private javax.swing.JLabel NomePaciente;
    private javax.swing.JButton NovaConsulta;
    private javax.swing.JPanel PainelGeral;
    private javax.swing.JLabel TelefonePaciente;
    private javax.swing.JLabel TextoBoasVindas;
    // End of variables declaration//GEN-END:variables
}
